#ifndef PUBLIC_OBJECTIVE_CARD_VIEW_CONSTANTS_H
#define PUBLIC_OBJECTIVE_CARD_VIEW_CONSTANTS_H

constexpr static double puocWidthToHeightRatio = 5.0 / (7.0);

#endif // PUBLIC_OBJECTIVE_CARD_VIEW_CONSTANTS_H